### ISSUE TITLE
能大概写下架构和思路吗?

### ISSUE THREAD

**Issue by jh235** [alberliu/goim#1]
正在学习楼主的代码,非常感谢代码条理和注释都很好,要是有个大概的架构和说明会更好了

**Comment by alberliu** [comment]
文档还不是很完善，以后会慢慢完善的，感谢你的支持

**Comment by Ryan0520** [comment]
@alberliu 我也一直在关注哦，楼主，非常感谢楼主分享代码，对我学习Go语言很有帮助。赞！👍👍👍👍👍👍👍👍
