### ISSUE TITLE
有没有安装文档

### ISSUE THREAD

**Issue by go-wolf** [alberliu/goim#12]
有没有安装文档 我没有看到安装文档

**Comment by alberliu** [comment]
暂时还没有安装文档，以后会慢慢完善的

**Comment by go-wolf** [comment]
能不能创建一个QQ群。好交流。我们项目准备用这个。能加一个QQ吗

**Comment by alberliu** [comment]
可以啊，我的QQ，568264999


 
---原始邮件---
发件人: "go-wolf"<notifications@github.com>
发送时间: 2019年7月12日(星期五) 中午12:24
收件人: "alberliu/goim"<goim@noreply.github.com>;
抄送: "State change"<state_change@noreply.github.com>;"Alber"<alber_liu@qq.com>;
主题: Re: [alberliu/goim] 有没有安装文档 (#12)



能不能创建一个QQ群。好交流。我们项目准备用这个。能加一个QQ吗
