### ISSUE TITLE
消息收发性能问题

### ISSUE THREAD

**Issue by yiippee** [alberliu/goim#16]
非常感谢作者写了一个这么好的IM例子。
有个疑问啊，每一个消息收发过程中，会涉及到查询是否在线，是否好友，登录设备等等一系列的查询数据库操作，会不会影响性能呢？因为每条消息都是这样做的。
还是我哪里理解错了吗？谢谢。

**Comment by alberliu** [comment]
是的，的确有严重的性能问题，因为第一版，性能没有考虑在范围内，只想先做出功能。现在正在写第二版，会加入缓存对性能进行优化。
