### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by Leadrive** [alberliu/goim#17]
logic/dao/friend.go

err := row.Scan(&friend.Id, &friend.UserId, &friend.Id, &friend.Label, &friend.CreateTime, &friend.UpdateTime)

应该是
err := row.Scan(&friend.Id, &friend.UserId, &friend.**FriendId**, &friend.Label, &friend.CreateTime, &friend.UpdateTime)

**Comment by alberliu** [comment]
好的，谢谢
