### ISSUE TITLE
您好  能解释一下这个函数吗

### ISSUE THREAD

**Issue by sclittleyu** [alberliu/goim#7]
在buffer.go 里面 有这个函数 readFromReader 我看您最终调用的是io.reader.Read这个接口，请问不需要实现这个接口就能直接调用吗？？？我很不明白这里 或者您直接实现了我没看到？

**Comment by alberliu** [comment]
buffer初始化的时候，是将net.Conn赋值给了reader io.Reader，实际调用的是net.Conn的方法
