### ISSUE TITLE
能部署吗，有服务器闲着，一直想做个即时通讯社区用？

### ISSUE THREAD

**Issue by DarkGost** [alberliu/goim#9]
能部署吗，有服务器闲着，一直想做个即时通讯社区用？咋联系？可以提供一些资金支持 希望能做下去！

**Comment by alberliu** [comment]
这个可以部署，只不过还是一个初版，距离生产环境使用还有许多需要开发，目前还在开发中，我会一直做下去的，不过主要还是工作，goim只是业余开发，开发进度会慢一点。
我的微信：18829291351
